name: Unit Test

on:
  # Trigger the workflow on all pull requests, and pushes to main
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt 
      
      - name: Run Unit Tests
        run: python3 -m unittest discover -v -s tests/ -p test*.py
